version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:2.13.0
    container_name: opensearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=nqwklXklwn6342*^&(

  server:
    build:
      context: .  # Use the current directory
      dockerfile: Docker/Dockerfile.server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
    depends_on:
      - opensearch

  client:
    build:
      context: .  # Use the current directory
      dockerfile: Docker/Dockerfile.client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
