# Dockerfile.client
FROM node:20-alpine

WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY client/package*.json /app/

RUN npm install

# Copy the rest of the client app
COPY client /app/

# Expose the port that your React app will run on
EXPOSE 5173

CMD ["npm", "run", "dev"]
