# Dockerfile.server
FROM node:20-alpine

WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY server/package*.json /app/

RUN npm install

# Copy the rest of the server app
COPY server /app/

# Expose necessary ports for your API
EXPOSE 3001

CMD ["npm", "run", "dev:app"]
